services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videoplayer-backend
    volumes:
      - ./backend/.workdir/videos.s3.db:/app/.workdir/videos.s3.db:rw
      - videoplayer-uploads:/app/.workdir/uploads:rw
      - videoplayer-conversion:/app/.workdir/conversion:rw
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - videoplayer-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://backend:4000
    container_name: videoplayer-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - videoplayer-network
    restart: always

networks:
  videoplayer-network:
    driver: bridge

volumes:
  videoplayer-uploads:
  videoplayer-conversion:
